version: "3.9"
services:
  hili:
    build: .
    command: python server.py /app/clips.json /app/assets
    volumes:
      - ./clips.json:/app/clips.json
      - ./assets:/app/assets
    ports:
      - "8888:8888"


